version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: inovaceifa-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    image: inovaceifa-api
    container_name: inovaceifa-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    image: inovaceifa-frontend
    container_name: inovaceifa-frontend
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  mysql_data: